### ISSUE TITLE
Negative numbers in arguments

### ISSUE THREAD

**Issue by tnkv** [alvkN/sharpass#3]
length argument can take negative numbers, which causes System.ArgumentOutOfRangeException
![image](https://github.com/alvkN/sharpass/assets/67426242/1df3ce0d-16ee-4a1e-904e-b64552b1be66)

The count argument also accepts negative numbers, but does not tell you that the count of passwords must be >= 1.
![image](https://github.com/alvkN/sharpass/assets/67426242/f7b3b152-675d-4f3d-bcb3-2e345a15051d)

**Comment by alvkN** [comment]
Fixed here #4
